config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations"}

  root to: 'welcome#index'

  resources :friendships
  resources :posts
  resources :users, only: [:show]
  get 'my_friends', to: 'users#my_friends'
  get 'search_friends', to: 'users#search'
  post 'add_friend', to: 'users#add_friend'

end

app/models/course.rb
class Course < ActiveRecord::Base
	belongs_to :user
	belongs_to :school
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, :class_name => 'User'
end

app/models/post.rb
class Post < ActiveRecord::Base
belongs_to :user
validates :content, presence: true

end

app/models/school.rb
class School < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :courses
  has_many :schools
  has_many :posts
  has_many :friendships
  has_many :friends, through: :friendships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


 scope :except_current_user,-> (user_id){
  select("*")
    .from("users")
    .where("id!=?", user_id)
    .order("id")
}
 scope :select_same_place,-> (user_id, city, country){
  select("*")
    .from("users")
    .where("id!=?", user_id)
    .where("city=?", city)
    .where("country=?", country)
 }

def full_name
  return "#{first_name} #{last_name}".strip if (first_name || last_name)
  "Anonymous"
end

def not_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1
end


def self.search(param)
  return User.none if param.blank?
  param.strip!
  param.downcase!
  (first_name_matches(param) + last_name_matches(param) + email_matches(param)).uniq
  # return email_matches(param)
end

def self.first_name_matches(param)
  matches('first_name', param)
end

def self.last_name_matches(param)
  matches('last_name', param)
end

def self.email_matches(param)
  matches('email', param)
end

def self.matches(field_name, param)
  where("#{field_name} ilike ?", "%#{param}%")
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

def destroy
	@friendship = current_user.friendships.where(friend_id: params[:id]).first
	@friendship.destroy
	flash[:danger] = "Friend successfully removed"
	redirect_to :back
end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :set_post, only: [:destroy]
  def new
  	@post = Post.new
  end

  def index
  	@posts = Post.order('created_at DESC')
  	@user = current_user
  end

  def show
  	@post = Post.find(params[:id])
  end

  def create
	@post = Post.new(post_params)
	@post.user_id = current_user.id
	if @post.save
		puts "if"
		flash[:success] = "Post successfully added"
		redirect_to root_path
	else
		puts "else"
		flash[:danger] = "cant post."
	end
  end

  def destroy
  	@post.destroy
  	redirect_to root_path
  end

  	private
  	def set_post
  		@post = Post.find(params[:id])
  	end
	def post_params
		params.require(:post).permit(:user_id, :content)
	end

end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
	before_filter :configure_permitted_parameters

	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :course, :school, :city, :country, :mobile])
		devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :course, :school, :city, :country, :mobile])
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def my_friends
		@friendships = current_user.friends
	end
	
	def search
		# @users = User.all
		@users = User.except_current_user(current_user.id)#.search(params[:search_param])
	
		# render status: :not_found, nothing: true unless @users.present?
	end

	def destroy

	end

	def show
		@user = User.find(params[:id])
		@posts = Post.all
	end

	def add_friend
		@friend = User.find(params[:friend])
		current_user.friendships.build(friend_id: @friend.id)
		if current_user.save
			redirect_to my_friends_path, notice: "Friend was successfully added."
		else
			redirect_to my_friends_path, flash[:error] = "There was an error with adding user as friend."
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@post = Post.new
  	@posts = Post.order('created_at DESC')
  	@user = current_user
  end

  def new
  	@post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/friends/_search.html.erb
<%= form_tag search_friends_path, remote: true, method: :get, id: 'friend-lookup-form' do %>
	<div class="form-group row no-padding text-center col-md-12">
		<div class="col-md-10">
			<%= text_field_tag :search_param, params[:search_param], 
								placeholder: "", 
								autofocus: true, 
								class: 'form-control search-box input-sm' %>
		</div>
		<div class ="col-md-2">
			<%= button_tag(type: :submit, class: 'btn btn-sm btn-success-outline') do %>
				<i class="fa fa-search">  Search for a friend</i>
			<% end %>
		</div>
	</div>
<% end %>
<!-- #############SEARCH RESULTS############
<% if @users %>
	<% if @users.size > 0 %>
		<div id="friend-lookup-results" class="well results-block col-md-10">
			<table class="search-results-table col-md-12">
				<tbody>
					<% @users.each do |user| %>
						<tr>
							<td><strong>Name:</strong> <%= user.full_name %></td>
							<td><strong>Email:</strong> <%= user.email %></td>
							<td>	<% if current_user.not_friends_with?(user.id) %>
									<%= link_to "Add as my friend", add_friend_path(user: current_user, friend: user), 
																	class: 'btn btn-sm btn-success-outline', 
																	method: :post %>
								<% else %>
									<span class="label label-primary">You are friends</span>
								<% end %>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	<% else %>
		<p class="lead col-md-12">No people matched this search criteria</p>
	<% end %>
<% end %>

 -->
<% if @users %>
		<% @users.each do |user| %>
			<% if user.id != current_user.id && (current_user.not_friends_with?(user.id)) %>
				<div align="center">
					<div class="col-xs-4">
						<div class="card text-xs-center">
						  <div class="card-header">
						    Hi I'm
						  </div>
						  <div class="card-block">
						    <h4 class="card-title"><%= user.full_name %> </h4>
						    <p class="card-text"><%= user.email %></p>
						    <%= link_to add_friend_path(user: current_user, friend: user), 
						    								:class => "btn btn-sm btn-success-outline btn-block", 
						    								method: :post do %>
						   	  <i class="fa fa-user-plus"> <strong>Add friend</strong> </i>
						    <% end %>
						    <%= link_to user_path(user), :class => "btn btn-sm btn-info-outline btn-block" do %>
						      <i class="fa fa-search"> <strong>View Profile</strong></i>
						    <% end %>
						  </div>
						  <div class="card-footer text-muted">
						    Online <%= time_ago_in_words(user.last_sign_in_at) %> ago
						  </div>
						</div>
					</div>
				</div>
			<% end %>
		<% end %>
<% end %>

app/views/layouts/_message.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-10 col-xs-offset-1">
			<% flash.each do |name, msg| %>
				<div class='alert alert-info' >
					<a href="#" class ="close" data-dismiss="alert">&#215;</a>
					<%= content_tag :div, msg, :id => "	flash_#{name}" if msg.is_a?(String	) %>
				</div>
	  		<% end %>
	  	</div>
	</div>
</div>

app/views/layouts/_navigation.html.erb
    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
<!--         <%= link_to "Post App", root_path, class: "navbar-brand" %> -->
        <% if current_user %>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
              <ul class="nav navbar-nav col-md-6">
                      <li><%= link_to "Home", root_path  %></li>
                      <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile</a>
                        <ul class="dropdown-menu">
                          <li><%= link_to "My Profile", user_path(current_user) %></li>
                          <li><a href="#"><%= link_to "Edit your profile", edit_user_registration_path(current_user) %></a></li>
                        </ul>
                      </li>
                      <li><%= link_to "My Friends", my_friends_path %></li>
                      <li><%= link_to "People", search_friends_path %></li>
              </ul>          
              <ul class="nav navbar-right col-md-4">
                  <li class="col-md-8 user-name text-right">
                    <i class="fa fa-user"></i>
                        <%= current_user.full_name %>
                  </li>
                  <li class="col-md-4 logout"><%= link_to("Log out", destroy_user_session_path, class: 'btn btn-danger-outline btn-sm ', method: :delete) %></li>
              </ul> 
            </div> 
        <% end %>
      </div>
    </div>

    
    <script type="text/javascript">
      $('.dropdown-toggle').dropdown()
    </script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PostApp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navigation' %>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
<!--           <%= bootstrap_flash %> -->
          <%= yield %>
        </div>
      </div><!--/row-->
    </div> <!-- /container -->

<!--     <div class="col-lg-2">
      <div class="well sidebar-nav">
        <h3>Sidebar</h3>
        <ul class="nav nav-list">
          <li class="nav-header">Sidebar</li>
          <li>link_to</li>
          <li>link_to</li>
          <li>link_to</li>
        </ul>
      </div>
    </div> -->



  </body>
</html>

app/views/posts/_post.html.erb
<%= form_for(@post, :remote => true, :html=> {class: "form-horizontal", role: "form"}) do |f| %>
	<% if user_signed_in? %>
		<div class="row">
			<div class="form-group text-area-size">		
				<%= f.text_area :content, class: "form-control text-area-res", placeholder: 'Say something' %>
			</div>
			<div class="form-group post-size">
					<%= f.submit class: 'btn btn-sm bbtn btn-success-outline btn-block' %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/posts/index.html.erb
	<% @posts.each do |post| %>
		<% if !current_user.not_friends_with?(post.user.id) || post.user.id == current_user.id %>
			<div class ="well well-sm">
				<b><%= link_to post.user.full_name, user_path(post.user) %></b>
				<div class="no-padding"><small><%= time_ago_in_words(post.created_at) %> ago</small></div><br>
				<p><%= post.content %></p>
				<% if current_user.id == post.user.id %>
					<%= link_to "Delete", post_path(post),  method: :delete, 
					                            data: { confirm: "Are you sure you want to delete this post?"} %>
				<% end %>
			</div>
		<% end %>
	<% end %>

app/views/users/friends.html.erb
<% if @friendships.count > 0 %>
	<% @friendships.each do |friends| %>
		<div class="col-lg-4">
			<div class="card">
			  <div class="card-block">
			    <h4 class="card-title"><%= friends.full_name %></h4>
			    <h6 class="card-subtitle text-muted"><small>Online <%= time_ago_in_words(friends.last_sign_in_at) %> ago</small></h6>
			  </div>
			  <img class="fixed-img" src="https://i.ytimg.com/vi/8VqcFj_11eA/maxresdefault.jpg" alt="Card image">
			  <div class="card-block">
			    <p class="card-text" align="center"><strong><%= friends.email %></strong></p>

			    <%= link_to user_path(friends), :class => "btn btn-sm btn-info-outline btn-block" do %>
			    	<i class="fa fa-search"> <strong>View Profile</strong></i>
			    <% end %>
		<!-- 	    <%= link_to "View", user_path(friends), class: "card-link" %> -->
		    	<%= link_to friendship_path(friends), method: :delete, :class => "btn btn-sm btn-danger-outline btn-block",
													  data: { confirm: "Are you sure you want to remove him/her to your friends list?"} do %>
					<i class="fa fa-times"> <strong>Remove</strong></i>
				<% end %>
<!-- 			    <%= link_to "Remove", friendship_path(friends), class: "card-link", method: :delete, 
																				data: { confirm: "Are you sure you want to remove him/her to your friends list?"} %> -->
			  </div>
			</div>
		</div>
	<% end %>
<% else %>
	<p class="lead col-md-12">No friends yet.</p>
<% end %>

app/views/users/index.html.erb
    <div class="container">
      <%= render 'posts/post' %>
    </div>

app/views/users/my_friends.html.erb
<% if @friendships.count > 0 %>

	<% @friendships.each do |friends| %>
		<div class="col-lg-4">
			<div class="card">
			  <div class="card-block">
			    <h4 class="card-title"><%= friends.full_name %></h4>
			    <h6 class="card-subtitle text-muted"><small>Online <%= time_ago_in_words(friends.last_sign_in_at) %> ago</small></h6>
			  </div>
			  <img class="fixed-img" src="https://i.ytimg.com/vi/8VqcFj_11eA/maxresdefault.jpg" alt="Card image">
			  <div class="card-block">
			    <p class="card-text" align="center"><strong><%= friends.email %></strong></p>

			    <%= link_to user_path(friends), :class => "btn btn-sm btn-info-outline btn-block" do %>
			    	<i class="fa fa-search"> <strong>View Profile</strong></i>
			    <% end %>
		<!-- 	    <%= link_to "View", user_path(friends), class: "card-link" %> -->
		    	<%= link_to friendship_path(friends), method: :delete, :class => "btn btn-sm btn-danger-outline btn-block",
													  data: { confirm: "Are you sure you want to remove him/her to your friends list?"} do %>
					<i class="fa fa-times"> <strong>Remove</strong></i>
				<% end %>
<!-- 			    <%= link_to "Remove", friendship_path(friends), class: "card-link", method: :delete, 
																				data: { confirm: "Are you sure you want to remove him/her to your friends list?"} %> -->
			  </div>
			</div>
		</div>
	<% end %>
<% else %>
	<p class="lead col-md-12">No friends yet.</p>
<% end %>

app/views/users/search.html.erb
<%= render 'friends/search' %>

app/views/users/search.js.erb
// alert("text");
$("#search-friend").html("<%= j (render '/friends/search') %>");

app/views/users/show.html.erb
<div class="col-lg-5">
	<img src="http://66.media.tumblr.com/7640c7eda1210e3c474a239c651fecc4/tumblr_nnzsvnbUzD1rlo1q2o1_1280.jpg" class="img-thumbnail fixed-img" alt="img" style="width:300px;height:250;">
	<div align="center"><small><%= @user.email %></small></div>	
    <div class="container-fluid">

         <h3 align="center"><%= @user.full_name %></h3>
         <ul class="nav nav-list">
          <small>
          <li class="nav-header"><i class="fa fa-home"></i> Lives in <%= link_to "#{@user.city},#{@user.country}" %></li>
          <li><i class="fa fa-graduation-cap"></i> Studied <%= link_to @user.course %> at <%= link_to @user.school %></li>
          <li><i class="fa fa-heart"></i> Single</li>
      <% if @user.friends.count > 0 %>    
          <% if @user.friends.count >1 %>
            <li><i class="fa fa-users"></i> <%= @user.friends.count %> friends </li>
          <% else %>
            <li><i class="fa fa-users"></i> <%= @user.friends.count %> friend </li>
          <% end %>
      <% end %>
          <li><i class="fa fa-mobile"></i> <%= @user.mobile %></li>
      <!-- new friends_path for other users' friends -->
          </small>
         </ul>

    </div>
</div>
<div class="col-lg-6">
<!-- 	<div class="well well-lg xl-well"> -->
    <% @posts.each do |post| %>
      <% if @user.id == post.user.id %>
        <div class ="well well-lg">
          <b><%= link_to post.user.full_name, user_path(post.user) %></b>
          <div class="no-padding"><small><%= time_ago_in_words(post.created_at) %> ago</small></div><br>
          <p><%= post.content %></p>
          <% if current_user.id == post.user.id %>
<!--             <a href="#"><small>·Delete</small></a> -->
            <%= link_to "Delete", post_path(post),  method: :delete, 
                                        data: { confirm: "Are you sure you want to delete this post?"} %>
          <% end %>
        </div>
      <% end %>
    <% end %>
<!-- 	</div> -->
</div>

app/views/welcome/index.html.erb
    <div class="container">
    	<div align="center">
      		<%= render 'posts/post' %>
      	</div>
      <%= render template: 'posts/index' %>
    </div>